name: NuGet Release

concurrency: ci-${{ github.ref }}

on:
  push:
    branches: [ main ] # Default release branch
    paths:
      - 'src/**'   
      - '.github/workflows/**' 

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  call-workflow-nuget-release:
    uses: Digitalroot-Valheim/.github/.github/workflows/nuget.release.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.NUGET_S3_REPO_KEY_ID }}
      aws-secret-access-key: ${{ secrets.NUGET_S3_REPO_KEY_SECRET }}
    with:
      sln-file-name: Digitalroot.Valheim.Common.Utils
      proj-file-name: Digitalroot.Valheim.Common.Utils
      skip-unit-tests: true
      nuget-gh-upload: true
      nuget-s3-upload: true
